//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.08 at 01:54:32 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://core.informatik.haw-hamburg.de/services/logging", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.haw_hamburg.informatik.core.services.logging;
